<a href="https://colab.research.google.com/github/mathfrenzy/ML/blob/main/Copy_of_Lab_1_Machine_Learning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Note: Make a copy of this and edit !!!**

##LAB 1 - Getting familiar with NumPy
Student Name:
<br>
Student ID:

In [2]:
#Importing relevant libraries
import numpy as np

Please refer to numpy documentation for help. Avoid using other sources (Chat GPT). Getting familiar with numpy is an essential skill for machine learning <br>
https://numpy.org/devdocs/user/absolute_beginners.html <br>
https://numpy.org/devdocs/reference/index.html#reference



#Part 1
Constructing numpy arrays

IMPORTANT:<br>
*   DO NOT USE LOOPS UNLESS SPECIFIED
*   USE NUMPY METHODS TO ANSWER THE QUESTIONS



**Question 1: Creating Arrays**
<br><br>
a$)$ Create and store a 1-D numpy array with the elements 1, 2, 3, 4 and print its shape
<br> <br>
b$)$ Create and store two other 1-D arrays, one with all ones and the other with all zeros. Make sure the size is the same as part a. Make sure to print the arrays and their shape.
<br> <br>
c$)$ Create a 1D numpy array with even numbers from 0 to 18 (Don't hard code this! use a numpy function and include 0 and 18 in the array). Make sure to print this array and its shape.
<br> <br>


In [16]:
a = np.arange(4) + 1
print(a)
print(a.shape)

b = np.ones(4)
c = np.zeros(4)
print(b)
print(b.shape)
print(c)
print(c.shape)

d = np.arange(0, 19, 2)
print(d)




[1 2 3 4]
(4,)
[1. 1. 1. 1.]
(4,)
[0. 0. 0. 0.]
(4,)
[ 0  2  4  6  8 10 12 14 16 18]


**Question 2: Manipulating arrays**

a) Create a 2-D array with 1 to 19 (Similar to part c) but this time reshape the array with 2 rows and 5 columns. Make sure to print this array and its shape
<br><br>
b) From the array you created in the first part, select the 1, 3, and 5th column store that in a new array and store the 2nd and 4th column in another array. Print both these arrays and their shape (Remember NO LOOPS and use array slicing to this question)
<br><br>
c) Create a boolean array where values are True if the corresponding element in the 2D array from part a is greater than 5, and False otherwise.
<br><br>

d) Create an array of size 10 with any value and print a new array where each element is replaced by its square root.

In [25]:
e = np.arange(1, 20, 2)
e = e.reshape(2, 5)
print(e)
print(e.shape)

temp = np.hsplit(e, 5)
f = np.hstack((temp[0], temp[2], temp[4]))
g = np.hstack((temp[1], temp[3]))
print(f)
print(f.shape)
print(g)
print(g.shape)

bool = e > 5
print(bool)

h = np.array([1, 4, 9, 16, 25, 36, 49, 64, 81, 100])
print(h)
i = np.sqrt(h)
print(i)

[[ 1  3  5  7  9]
 [11 13 15 17 19]]
(2, 5)
[[ 1  5  9]
 [11 15 19]]
(2, 3)
[[ 3  7]
 [13 17]]
(2, 2)
[[False False False  True  True]
 [ True  True  True  True  True]]
[  1   4   9  16  25  36  49  64  81 100]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


**Question 3: Operating arrays** <br><br>
a) Create 2 arrays, 1-D array ranging from 1 to 10 (inclusive), 2-D array 10 to 1 (inclusive) and add them element wise (Remember NO LOOPS). Print the resulting array and its shape
<br><br>
b) Create an array  -3 to 6 (inclusive) and do the dot product from the resulting array from part a. (Manipulate the the array shapes so the dot product works and make sure the resulting array is a scalar). Print the resulting value.
<br><br>
c) Generate a 3x3 array with random values between 0 and 1 using numpy's random module and take the inverse of the matrix and element wise multiply the resulting array by 10. Print the resulting array and its shape.

In [48]:
j = np.arange(10) + 1
k = np.arange(10, 5, -1)
l = np.arange(5, 0, -1)
m = np.vstack((k, l))
n = j + m.flatten()
print(n)
print(n.shape)

p = np.arange(-3, 7, 1)
q = n.dot(p)
print(q)

r = np.random.default_rng().random((3, 3))
r = np.linalg.inv(r)
r = r * 10
print(r)
print(r.shape)

[11 11 11 11 11 11 11 11 11 11]
(10,)
165
[[ 33.38194906 -23.59034467 -12.97891442]
 [  9.43714535  13.21616591  -8.55490347]
 [-51.45137746  34.01323962  42.19707957]]
(3, 3)


**Challenge Questions** <br> <br>
a) Create a 3D numpy array of shape 4x4x4 with random values. Perform the following operations: <br> <br>
Replace all values greater than the mean of the entire array with 1.
Replace all values less than the mean of each individual 2D array along the third dimension with 0.
<br><br>
b) Generate a 3D array with dimensions (3, 5, 4) containing random integers. Extract a 2D array by taking the sum along the third dimension.

In [52]:
s = np.random.default_rng().integers(10, size=(4, 4, 4))
print(s)
t = s.mean()
for x in range(len(s)):
  u = s[x].mean()
  for y in range(len(s[0])):
    for z in range(len(s[0][0])):
      if s[x][y][z] > t:
        s[x][y][z] = 1
      if s[x][y][z] < u:
        s[x][y][z] = 0
print(s)

v = np.random.default_rng().integers(10, size=(3, 5, 4))
print(v)
w = v[0] + v[1] + v[2]
print(w)


[[[9 8 1 3]
  [1 1 3 5]
  [2 2 4 1]
  [5 5 2 6]]

 [[1 4 7 0]
  [4 8 1 2]
  [0 8 9 5]
  [8 1 9 3]]

 [[3 3 8 3]
  [7 9 4 4]
  [8 6 0 1]
  [2 8 6 4]]

 [[3 8 7 5]
  [7 7 3 1]
  [4 9 7 6]
  [0 8 9 6]]]
[[[0 0 0 0]
  [0 0 0 0]
  [0 0 4 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
[[[5 3 5 3]
  [5 4 3 7]
  [4 1 1 1]
  [0 7 1 5]
  [3 3 0 2]]

 [[5 2 4 2]
  [7 2 1 2]
  [3 1 8 3]
  [1 7 9 8]
  [8 9 5 6]]

 [[5 3 4 8]
  [5 7 3 3]
  [5 3 0 1]
  [1 0 8 3]
  [1 3 3 0]]]
[[15  8 13 13]
 [17 13  7 12]
 [12  5  9  5]
 [ 2 14 18 16]
 [12 15  8  8]]


#Part 2
Linear Regression

IMPORTANT:<br>
*   DO NOT USE LOOPS UNLESS SPECIFIED
*   USE NUMPY METHODS TO ANSWER THE QUESTIONS



In [ ]:
#DO NOT EDIT
np.random.seed(0)
X = 0.0000002*np.random.normal(size=(20,1)) + 0.34

#Ground Truth
weights = np.array([2,-3]).reshape(-1,1)
y = np.dot(X,weights)

solved_weights = []
#Using the least squares regression method from numpy try to solve for the weights
#and see if it atches the ground truth
## YOUR CODE HERE
## END

if np.allclose(weights, solved_weights):
  print("Lab 1 Finished!")
else:
  print("Please check your weights again")

NameError: name 'w' is not defined